name: hello world

inputs:
  who:
    description: who to greet
    required: true

outputs:
  time:
    description: 'time we said hello'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who }}
