name: GitHub Actions Demo
on: 
  push: 
    branches: [main]
    branches-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "triggered by: ${{github.event.name}}"
          echo "using branch: ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - name: list files
        run: |
          echo "rep ${{github.repository}} contains: "
          tree
